apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: D:\Conestoga\Course2-DevOps\Sem2\ContainerOrchestration\FinalProject\final-assignment-crm\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: adminer-container
  name: adminer-container
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: adminer-container
  template:
    metadata:
      annotations:
        kompose.cmd: D:\Conestoga\Course2-DevOps\Sem2\ContainerOrchestration\FinalProject\final-assignment-crm\kompose.exe convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: adminer-container
    spec:
      containers:
        - env:
            - name: ADMINER_DEFAULT_SERVER
              value: db
          image: adminer:latest
          name: adminer-container
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
